on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v3
      - name: Insert .env File
        run: echo "TOKEN=${{ secrets.BOT_TOKEN }}" > .env
      - name: Build Image
        run: docker build --tag staffping:latest .
      - name: Export Image to .tar File
        run: docker save -o ./staffping.tar staffping:latest
      - name: Copy File to Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_KEY }}
          port: 22
          source: "staffping.tar"
          target: "images"
